version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=teste_quiker_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
    command: sh -c "npm install && npm run init"
  
  react:
    build:
      context: ./react-posts
      dockerfile: Dockerfile
    container_name: react_container
    ports:
      - "3000:3000"
    volumes:
      - ./react-posts:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]

  db:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste_quiker_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
